name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npx vitest run src/tests/PostService.test.ts

    e2e-tests:
        name: E2E Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install global dependencies
              run: npm install -g ts-node-dev pnpm

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Build project
              run: npm run build || echo "No build script found, continuing..."

            - name: Start server and run Playwright tests
              run: |
                  # Démarrer le serveur en arrière-plan avec npx pour s'assurer que ts-node-dev est disponible
                  npx ts-node-dev --respawn src/index.ts &
                  # Attendre que le serveur soit prêt
                  sleep 15
                  # Exécuter les tests Playwright
                  npx playwright test
              env:
                  # Ajouter les variables d'environnement nécessaires
                  NODE_ENV: test

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
