name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

            - name: Run unit tests
              run: npx vitest run --exclude "src/tests/e2e/**/*.spec.ts"

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Start server and run E2E tests
              run: |
                  npx kill-port 3009 || true
                  npx ts-node src/index.ts &
                  sleep 5
                  npx playwright test --config playwright.config.ts
              env:
                  CI: true

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
