name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npx vitest run src/tests/PostService.test.ts

    e2e-tests:
        name: E2E Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install global dependencies
              run: npm install -g ts-node-dev pnpm

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Build project
              run: npm run build || echo "No build script found, continuing..."

            - name: Start server
              run: |
                  # Démarrer le serveur en arrière-plan
                  npx ts-node-dev --respawn src/index.ts &
                  # Attendre que le serveur soit prêt
                  sleep 15
                  echo "Server should be running now"
              env:
                  NODE_ENV: test

            - name: Run Playwright tests
              run: |
                  # Désactiver la configuration webServer de Playwright
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 PLAYWRIGHT_SKIP_VALIDATION=1 npx playwright test --browser=chromium
              env:
                  NODE_ENV: test
                  # Indiquer l'URL de base pour les tests
                  BASE_URL: http://localhost:3009

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
