name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npx vitest run src/tests/PostService.test.ts

    e2e-tests:
        name: E2E Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install global dependencies
              run: npm install -g ts-node-dev

            - name: Install Playwright
              run: npx playwright install --with-deps chromium

            - name: Create simple Playwright config
              run: |
                  cat > playwright.ci.config.js << 'EOL'
                  // @ts-check
                  const { defineConfig } = require('@playwright/test');

                  module.exports = defineConfig({
                    testDir: './src/tests/e2e',
                    fullyParallel: false,
                    forbidOnly: true,
                    retries: 0,
                    workers: 1,
                    reporter: 'html',
                    use: {
                      baseURL: 'http://localhost:3009',
                      screenshot: 'only-on-failure',
                      trace: 'on-first-retry',
                    },
                    projects: [
                      {
                        name: 'chromium',
                        use: { browserName: 'chromium' },
                      },
                    ],
                    /* Pas de configuration webServer pour éviter les conflits */
                  });
                  EOL

            - name: Start server and run tests
              run: |
                  # Démarrer le serveur en arrière-plan
                  npx ts-node-dev src/index.ts &
                  PID=$!
                  echo "Server started with PID $PID"

                  # Attendre que le serveur soit prêt
                  echo "Waiting for server to be ready..."
                  timeout 30 bash -c 'until curl -s http://localhost:3009 > /dev/null; do sleep 1; done' || echo "Server may not be ready, but continuing anyway"

                  # Exécuter les tests Playwright
                  echo "Running Playwright tests..."
                  npx playwright test --config=playwright.ci.config.js

                  # Arrêter le serveur à la fin
                  echo "Stopping server..."
                  kill $PID || true
              env:
                  NODE_ENV: test
                  # Désactiver explicitement l'auto-démarrage du serveur
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
                  PLAYWRIGHT_SKIP_VALIDATION: 1

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
